### ISSUE TITLE
Measures vs Dimentions

### ISSUE THREAD

**Issue by pfbox** [deep-bi/spark-druid-segment-reader#5]
Hi guys, 
I'm not sure if the question makes sense, but we are trying to use your library and we noticed that only Dimensions are processes and no measures, just curious if it's possible to extract measures as well?
Regards,
Pavel

**Comment by cmick** [comment]
Your observation is correct. It's currently one of the limitations of the tool as it only recognizes the dimensions. Although it would be possible to extend it to at least recognize simple metrics (counts, sums, etc). At some point we wanted to add this metric extraction but it landed in our backlog. Would you be interested in such a feature?

**Comment by pfbox** [comment]
Sure, absolutely. We just started using your library and measures would be a big help.

**Comment by cmick** [comment]
fixed in #7

**Comment by BartMiki** [comment]
Hi @pfbox !

We published a new version of the reader here: https://github.com/deep-bi/spark-druid-segment-reader/releases/tag/release-0.4.0. This version supports both metrics and dimensions out of the box. You should be able to see your metrics now in the data frame.
